wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713100042.0
    t:
      1:
      - 49
      - 51
      - 53
      - 55
      - 92
      - 95
      - 96
      - 97
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 92
      - 95
      - 96
      - 97
      - 105
      3:
      - 23
      4: 3.11.6
      5: 0.16.6
      8:
      - 5
      - 9
      13: linux-x86_64
    framework: huggingface
